/*
Deployment script for EJournalDBTest

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "EJournalDBTest"
:setvar DefaultFilePrefix "EJournalDBTest"
:setvar DefaultDataPath "E:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\"
:setvar DefaultLogPath "E:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS ON,
                ANSI_PADDING ON,
                ANSI_WARNINGS ON,
                ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                QUOTED_IDENTIFIER ON,
                ANSI_NULL_DEFAULT ON,
                CURSOR_DEFAULT LOCAL,
                RECOVERY FULL 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET PAGE_VERIFY NONE 
            WITH ROLLBACK IMMEDIATE;
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET TARGET_RECOVERY_TIME = 0 SECONDS 
    WITH ROLLBACK IMMEDIATE;


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET QUERY_STORE (QUERY_CAPTURE_MODE = ALL, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 367), MAX_STORAGE_SIZE_MB = 100) 
            WITH ROLLBACK IMMEDIATE;
    END


GO
PRINT N'Rename refactoring operation with key c76c9f35-9d70-4e3e-b377-ddd7802de44f is skipped, element [dbo].[Exercises].[Dedline] (SqlSimpleColumn) will not be renamed to Deadline';


GO
PRINT N'Rename refactoring operation with key e1cbb174-0180-4db5-abaa-f7d88b6e7a38 is skipped, element [dbo].[UpdateStudents] (SqlProcedure) will not be renamed to [UpdateStudent]';


GO
PRINT N'Rename refactoring operation with key 51c83756-1b2e-4a1b-8bf7-7b137008ff79 is skipped, element [dbo].[UpdateGroups] (SqlProcedure) will not be renamed to UpdateGroup';


GO
PRINT N'Rename refactoring operation with key 5492cd3d-bf97-41f7-a239-1d865c558482 is skipped, element [dbo].[UpdateExercises] (SqlProcedure) will not be renamed to UpdateExercise';


GO
PRINT N'Rename refactoring operation with key 84d881a3-5cf0-4c95-ba65-63c531de6b9d is skipped, element [dbo].[UpdateComments] (SqlProcedure) will not be renamed to [UpdateComment]';


GO
PRINT N'Move Schema refactoring operation with key d12f3314-a6e4-4bb2-b4c8-b9d24e978a44 is skipped, model element [dbo].[Attendances] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 22a2eff6-3c1c-43bf-a4ef-478170643093 is skipped, model element [dbo].[Comments] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 0c1e13ce-2f71-44ff-9a56-fa529799cec1 is skipped, model element [dbo].[CommentTypes] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 4d18e2a9-66cd-4f34-b3a0-4afb890d917b is skipped, model element [dbo].[Courses] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key cb0539ca-5113-4ef0-a7d7-165953408f25 is skipped, model element [dbo].[Exercises] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 911940ea-3372-4251-b813-3afb0e247958 is skipped, model element [dbo].[Groups] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 9102c62f-df54-4013-8675-95426358be13 is skipped, model element [dbo].[GroupStudents] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 65325c3c-8318-4db5-b28f-3608a19ba5aa is skipped, model element [dbo].[Lessons] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 3f18f33f-5cb6-494b-ab79-e0c72a0fd0c0 is skipped, model element [dbo].[Projectes] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 92947128-73ca-4eab-a1c5-4864bef6be3e is skipped, model element [dbo].[ProjectGroups] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key f8233e83-6691-45db-a15e-267dc882eda3 is skipped, model element [dbo].[Students] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 2149a70d-5424-437e-b07b-0a68f41ce784 is skipped, model element [dbo].[StudentsComments] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 3fbbcb5a-e21e-42fc-8efb-ebae4b3b71ed is skipped, model element [dbo].[StudentsExercises] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 4b062bd7-d292-4df2-8127-a02f2a0b1d8e is skipped, model element [dbo].[StudetsProjectGroup] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key e51d908f-eb35-4b7f-bbf2-dff852b0b714 is skipped, model element [dbo].[AddCourse] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key a2cb90ba-7243-4c52-8288-00b3b3e4f02c is skipped, model element [dbo].[CountGroupsByCourse] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key d023875f-9fdf-4f34-a14d-1b136456bad8 is skipped, model element [dbo].[DeleteCourse] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key e33188be-4438-4f68-833d-96096257fb50 is skipped, model element [dbo].[GetAllCourses] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key f911cc75-65e7-4edd-8253-713e290da397 is skipped, model element [dbo].[GetCourse] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 1b8afff2-9642-48c9-a11f-4a3f083a2831 is skipped, model element [dbo].[UpdateCourse] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key f22d4a80-cc30-4e09-a102-98fdd5873e62 is skipped, model element [dbo].[StudentAttendance] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 1d0e8087-3307-4783-b986-1b3c033f7711 is skipped, model element [dbo].[UpdateGroup] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 949971e8-3af4-40f1-bbe3-14069ff2f8bf is skipped, model element [dbo].[GetStudentByGroup] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 1b14a86d-3c7a-438c-b1ab-108693c07be3 is skipped, model element [dbo].[GetGroup] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 20688625-2990-4672-8f4e-3355c2501504 is skipped, model element [dbo].[GetAllGroupsWithCourses] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key f8befadf-c09f-4901-94d3-3c85eada6b24 is skipped, model element [dbo].[GetAllGroups] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 8fa63505-caef-47fd-9993-c48fb10900cd is skipped, model element [dbo].[DeleteGroup] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 8f70e344-bef6-48df-9cef-467f1f2b4388 is skipped, model element [dbo].[AddGroup] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key b81b07bf-d378-495e-bf54-ad79ca9cc9c0 is skipped, model element [dbo].[AddComment] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 7350b9cf-a45b-48fa-9ae3-429ab85f8526 is skipped, model element [dbo].[AddExercises] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 0c30a566-cd2f-4dcc-8ab7-5e2e3fdb2914 is skipped, model element [dbo].[AddStudentsAttendance] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 4551274c-5889-436c-b349-7f7894d629b2 is skipped, model element [dbo].[AddStudent] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 5469a293-29e0-4efd-bcd7-86cbe74417f4 is skipped, model element [dbo].[AddProjectGroup] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key b3301991-52c1-421a-927c-0130936eb069 is skipped, model element [dbo].[AddProject] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key de7011f7-0426-4212-8f06-4327939311a2 is skipped, model element [dbo].[AddLesson] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 7123f726-1a02-4157-833a-d69c0ededff2 is skipped, model element [dbo].[AddHomeWork] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 2f610d05-7c82-4a45-8a90-211807b75e62 is skipped, model element [dbo].[GetAllProjectGroups] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 9e8d6164-b610-4133-9bfc-eeaab7910de6 is skipped, model element [dbo].[GetAllExercises] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 699c3874-d9b3-4f39-a007-e8a5d1dd0ffe is skipped, model element [dbo].[GetAllComments] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 6a21a3db-c013-4499-b72c-c3e48080b130 is skipped, model element [dbo].[DeleteStudent] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 612020c7-4a59-4426-b8b9-bbed128e664f is skipped, model element [dbo].[DeleteProjectGroup] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 3d252922-a645-4714-9c55-7aadb517841a is skipped, model element [dbo].[DeleteProject] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 03896420-7dfe-4c76-9240-41b771dfe8fe is skipped, model element [dbo].[DeleteLessonAndAttendances] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key ba3f7240-9ca9-4fd0-9ef3-3717107907f9 is skipped, model element [dbo].[DeleteExercises] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 5d0a958d-e107-4cdb-bb67-e9a6ee5aab76 is skipped, model element [dbo].[DeleteComments] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key ff09aff9-5a15-4b59-b82e-71c8a28542bc is skipped, model element [dbo].[AddStudentToProjectGroup] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 82428f47-776b-4c41-afe4-b5031e13ce17 is skipped, model element [dbo].[UpdateLesson] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 048c54df-157f-4bd4-a496-b118ab86d11d is skipped, model element [dbo].[UpdateHomeWork] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key e03757eb-2efa-47a4-b9e4-0c209b5de448 is skipped, model element [dbo].[UpdateExercise] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 77fcbbbf-4fe0-4847-a43b-2f342c44ee38 is skipped, model element [dbo].[UpdateComment] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key d6c0fc37-c92e-4184-9a88-0ba0b50d4c46 is skipped, model element [dbo].[GetStudent] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 9e790da1-75a4-4245-8b29-b14722f0e59e is skipped, model element [dbo].[GetProjects] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 92cc071b-3a60-45e1-ba85-d3a74b510bf6 is skipped, model element [dbo].[GetProjectGroup] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 623bfe98-41b2-4896-a8ba-a78d80122e35 is skipped, model element [dbo].[GetProject] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key d2117cef-43d5-4877-a4d8-2dc28be721c5 is skipped, model element [dbo].[GetListStudentsInOneProjectGroup] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key d26343e3-9855-43c8-b574-068b03326b22 is skipped, model element [dbo].[GetLessonsByGroup] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 277a0e55-de0b-4c3c-a7ce-39e8f21cc7ca is skipped, model element [dbo].[GetLessonsAttendancesByGroup] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key b3d16265-df13-4a31-845a-08ddb69007de is skipped, model element [dbo].[GetLessons] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 63efc32e-2ffd-4db9-b143-46dad000cf68 is skipped, model element [dbo].[GetLesson] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 97f1cf5a-61cd-40e5-ba57-5cca0accbaba is skipped, model element [dbo].[GetGroupsAndNumberOfStudentsInThemAndGroupStatus] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 8206096c-9347-4015-ab89-e4156888a263 is skipped, model element [dbo].[GetGroupAndStudentsInIt] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key fdf24e13-66ea-4c27-8420-cf0bbcf72cac is skipped, model element [dbo].[GetExercises] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key c19a56f0-6639-4fb0-867d-48b28dad8b6a is skipped, model element [dbo].[GetExercise] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 35b3281f-3f99-4bbb-ba93-3a98c08e08f1 is skipped, model element [dbo].[GetComment] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 902b0ff0-5984-40d3-b026-717ef143073e is skipped, model element [dbo].[GetAllStudents] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 5ef66b66-750e-44be-8a9d-a3cc591e7b2c is skipped, model element [dbo].[UpdateStudent] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 6f986ea6-2516-4041-9c95-3ced1e4093ad is skipped, model element [dbo].[UpdateProjectGroup] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 5475933e-a26a-4ae6-8432-1ec3f57681dc is skipped, model element [dbo].[UpdateProject] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key e9e19888-cbd1-44ab-b0c3-012314bce07b is skipped, model element [dbo].[UpdateLessonAttendances] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 485ca62c-8589-4d38-acc4-5017c154acd2 is skipped, model element [dbo].[AddExerciseToStudent] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key d78e75b1-2029-46f3-aa81-cd237f32a9c8 is skipped, model element [dbo].[GetStudentsNotAreInGroup] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 69bdbe73-0e5f-499e-b1d5-016355635c15 is skipped, model element [dbo].[GetCommentsByStudent] is not found in target database.';


GO
PRINT N'Rename refactoring operation with key c918fe73-45aa-41e4-8831-4d7db2f1d497 is skipped, element [EJournal].[Comments].[IdCommentType] (SqlSimpleColumn) will not be renamed to CommentType';


GO
PRINT N'Move Schema refactoring operation with key 807f19f4-d716-4671-821b-80ac9faaa589 is skipped, model element [dbo].[SearchStudentAgreementNumber] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key bf1efd99-2760-450b-8394-354e7422a14d is skipped, model element [dbo].[SearchStudentAll] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 463d532d-8a3f-4e7f-933c-39a7f3e08c32 is skipped, model element [dbo].[SearchStudentCity] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 23f28e1e-9a25-42f0-856f-d11e6023f32f is skipped, model element [dbo].[SearchStudentCours] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 95371095-7ce9-4c01-adec-0a5914daaba3 is skipped, model element [dbo].[SearchStudentsPhone] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 3a046aa4-31d9-4b50-9f15-65689196b639 is skipped, model element [dbo].[SearchStydentsNameSername] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key f7d6fce3-af2d-44a0-9f56-0cc295c9ae80 is skipped, model element [dbo].[SearchStydentsSername] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key ede7f9c9-d388-4f29-aa2c-da753bb404fa is skipped, model element [dbo].[SearchStudentsEmail] is not found in target database.';


GO
PRINT N'Move Schema refactoring operation with key 7d3e1348-bf60-473b-a7d3-638252fac761 is skipped, model element [dbo].[SearcStudentsGroup] is not found in target database.';


GO
PRINT N'Rename refactoring operation with key d8dc6697-1576-427d-941e-8b953900518f is skipped, element [EJournal].[Comments].[Comment] (SqlSimpleColumn) will not be renamed to [CommentText]';


GO
PRINT N'Creating Schema [EJournal]...';


GO
CREATE SCHEMA [EJournal]
    AUTHORIZATION [dbo];


GO
PRINT N'Creating User-Defined Table Type [EJournal].[StudentAttendance]...';


GO
CREATE TYPE [EJournal].[StudentAttendance] AS TABLE (
    [LessonsIds] INT NULL,
    [StudentId]  INT NULL,
    [isPresense] BIT NULL);


GO
PRINT N'Creating User-Defined Table Type [EJournal].[StudentExercise]...';


GO
CREATE TYPE [EJournal].[StudentExercise] AS TABLE (
    [IdStudent]  INT NULL,
    [IdExercise] INT NULL,
    [Points]     INT NULL);


GO
PRINT N'Creating User-Defined Table Type [EJournal].[GroupIdsStudentsIds]...';


GO
CREATE TYPE [EJournal].[GroupIdsStudentsIds] AS TABLE (
    [IdGroup]    INT NULL,
    [IdStudents] INT NULL);


GO
PRINT N'Creating User-Defined Table Type [EJournal].[StudentsComment]...';


GO
CREATE TYPE [EJournal].[StudentsComment] AS TABLE (
    [IdStudent] INT NULL,
    [IdComment] INT NULL);


GO
PRINT N'Creating User-Defined Table Type [EJournal].[StudentsIds]...';


GO
CREATE TYPE [EJournal].[StudentsIds] AS TABLE (
    [IdProjectGroup] INT NULL,
    [IdStudent]      INT NULL);


GO
PRINT N'Creating Table [EJournal].[ProjectGroups]...';


GO
CREATE TABLE [EJournal].[ProjectGroups] (
    [Id]        INT            IDENTITY (1, 1) NOT NULL,
    [Name]      NVARCHAR (100) NOT NULL,
    [IdProject] INT            NOT NULL,
    [Mark]      INT            NOT NULL,
    CONSTRAINT [PK_PROJECTGROUPS] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [EJournal].[Projectes]...';


GO
CREATE TABLE [EJournal].[Projectes] (
    [Id]          INT            IDENTITY (1, 1) NOT NULL,
    [Name]        NVARCHAR (50)  NOT NULL,
    [Description] NVARCHAR (255) NOT NULL,
    [IsDelete]    BIT            NOT NULL,
    CONSTRAINT [PK_PROJECTES] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [EJournal].[Comments]...';


GO
CREATE TABLE [EJournal].[Comments] (
    [Id]          INT            IDENTITY (1, 1) NOT NULL,
    [CommentText] NVARCHAR (255) NOT NULL,
    [CommentType] NVARCHAR (100) NOT NULL,
    CONSTRAINT [PK_COMMENTS] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [EJournal].[StudetsProjectGroup]...';


GO
CREATE TABLE [EJournal].[StudetsProjectGroup] (
    [IdStudent]      INT NOT NULL,
    [IdProjectGroup] INT NOT NULL
);


GO
PRINT N'Creating Table [EJournal].[StudentsComments]...';


GO
CREATE TABLE [EJournal].[StudentsComments] (
    [IdComment] INT NOT NULL,
    [IdStudent] INT NOT NULL
);


GO
PRINT N'Creating Table [EJournal].[StudentsExercises]...';


GO
CREATE TABLE [EJournal].[StudentsExercises] (
    [IdStudent]  INT NOT NULL,
    [IdExercise] INT NOT NULL,
    [Point]      INT NULL
);


GO
PRINT N'Creating Table [EJournal].[Lessons]...';


GO
CREATE TABLE [EJournal].[Lessons] (
    [Id]         INT            IDENTITY (1, 1) NOT NULL,
    [IdGroup]    INT            NOT NULL,
    [DateLesson] DATETIME       NOT NULL,
    [Topic]      NVARCHAR (250) NULL,
    CONSTRAINT [PK_LESSONS] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [EJournal].[GroupStudents]...';


GO
CREATE TABLE [EJournal].[GroupStudents] (
    [IdGroup]    INT NOT NULL,
    [IdStudents] INT NOT NULL
);


GO
PRINT N'Creating Table [EJournal].[Groups]...';


GO
CREATE TABLE [EJournal].[Groups] (
    [Id]       INT            IDENTITY (1, 1) NOT NULL,
    [Name]     NVARCHAR (100) NOT NULL,
    [IdCourse] INT            NOT NULL,
    [IsFinish] BIT            NOT NULL,
    [IsDelete] BIT            NOT NULL,
    CONSTRAINT [PK_GROUPS] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [EJournal].[Exercises]...';


GO
CREATE TABLE [EJournal].[Exercises] (
    [Id]           INT            IDENTITY (1, 1) NOT NULL,
    [IdGroup]      INT            NOT NULL,
    [Description]  NVARCHAR (255) NOT NULL,
    [Deadline]     DATETIME       NULL,
    [ExerciseType] NVARCHAR (250) NULL,
    [IsDelete]     BIT            NOT NULL,
    CONSTRAINT [PK_EXERCISES] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [EJournal].[Courses]...';


GO
CREATE TABLE [EJournal].[Courses] (
    [Id]       INT            IDENTITY (1, 1) NOT NULL,
    [Name]     NVARCHAR (100) NOT NULL,
    [IsDelete] BIT            NOT NULL,
    CONSTRAINT [PK_COURSENAMES] PRIMARY KEY CLUSTERED ([Id] ASC),
    UNIQUE NONCLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [EJournal].[Attendances]...';


GO
CREATE TABLE [EJournal].[Attendances] (
    [IdLesson]   INT NOT NULL,
    [IdStudent]  INT NOT NULL,
    [IsPresence] BIT NOT NULL
);


GO
PRINT N'Creating Table [EJournal].[Students]...';


GO
CREATE TABLE [EJournal].[Students] (
    [Id]                INT            IDENTITY (1, 1) NOT NULL,
    [Name]              NVARCHAR (100) NOT NULL,
    [Surname]           NVARCHAR (100) NOT NULL,
    [Email]             NVARCHAR (100) NOT NULL,
    [Phone]             NVARCHAR (16)  NOT NULL,
    [Git]               NVARCHAR (100) NULL,
    [City]              NVARCHAR (MAX) NULL,
    [TeacherAssessment] INT            NOT NULL,
    [Ranking]           FLOAT (53)     NOT NULL,
    [AgreementNumber]   NVARCHAR (50)  NOT NULL,
    [IsDelete]          BIT            NOT NULL,
    CONSTRAINT [PK_STUDENTS] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Default Constraint [EJournal].[DF__ProjectGroups__Mark__239E4DCF]...';


GO
ALTER TABLE [EJournal].[ProjectGroups]
    ADD CONSTRAINT [DF__ProjectGroups__Mark__239E4DCF] DEFAULT ((100)) FOR [Mark];


GO
PRINT N'Creating Default Constraint [EJournal].[DF__Projects__IsDele__239E4DCF]...';


GO
ALTER TABLE [EJournal].[Projectes]
    ADD CONSTRAINT [DF__Projects__IsDele__239E4DCF] DEFAULT ((0)) FOR [IsDelete];


GO
PRINT N'Creating Default Constraint unnamed constraint on [EJournal].[Groups]...';


GO
ALTER TABLE [EJournal].[Groups]
    ADD DEFAULT ((0)) FOR [IsFinish];


GO
PRINT N'Creating Default Constraint [EJournal].[DF__Groups__IsDele__239E4DCF]...';


GO
ALTER TABLE [EJournal].[Groups]
    ADD CONSTRAINT [DF__Groups__IsDele__239E4DCF] DEFAULT ((0)) FOR [IsDelete];


GO
PRINT N'Creating Default Constraint [EJournal].[DF__Exercises__IsDele__239E4DCF]...';


GO
ALTER TABLE [EJournal].[Exercises]
    ADD CONSTRAINT [DF__Exercises__IsDele__239E4DCF] DEFAULT ((0)) FOR [IsDelete];


GO
PRINT N'Creating Default Constraint [EJournal].[DF__CourseNames__IsDelete]...';


GO
ALTER TABLE [EJournal].[Courses]
    ADD CONSTRAINT [DF__CourseNames__IsDelete] DEFAULT ((0)) FOR [IsDelete];


GO
PRINT N'Creating Default Constraint unnamed constraint on [EJournal].[Attendances]...';


GO
ALTER TABLE [EJournal].[Attendances]
    ADD DEFAULT ((1)) FOR [IsPresence];


GO
PRINT N'Creating Default Constraint unnamed constraint on [EJournal].[Students]...';


GO
ALTER TABLE [EJournal].[Students]
    ADD DEFAULT 100 FOR [TeacherAssessment];


GO
PRINT N'Creating Default Constraint unnamed constraint on [EJournal].[Students]...';


GO
ALTER TABLE [EJournal].[Students]
    ADD DEFAULT 100 FOR [Ranking];


GO
PRINT N'Creating Default Constraint [EJournal].[DF__Students__IsDele__239E4DCF]...';


GO
ALTER TABLE [EJournal].[Students]
    ADD CONSTRAINT [DF__Students__IsDele__239E4DCF] DEFAULT ((0)) FOR [IsDelete];


GO
PRINT N'Creating Foreign Key [EJournal].[Attendances_Lessons_Id]...';


GO
ALTER TABLE [EJournal].[Attendances] WITH NOCHECK
    ADD CONSTRAINT [Attendances_Lessons_Id] FOREIGN KEY ([IdLesson]) REFERENCES [EJournal].[Lessons] ([Id]);


GO
PRINT N'Creating Procedure [EJournal].[DeleteGroupAndGroupStudent]...';


GO
CREATE PROCEDURE [EJournal].[DeleteGroupAndGroupStudent] @IdGroup INT
AS
DELETE
FROM [EJournal].[GroupStudents]
WHERE IdGroup = @IdGroup;

DELETE
FROM Groups
WHERE Id = @IdGroup
GO
PRINT N'Creating Procedure [EJournal].[AddGroup]...';


GO
CREATE PROCEDURE [EJournal].[AddGroup] @Name NVARCHAR(100),
	@IdCourse INT
AS
INSERT INTO [EJournal].[Groups] (
	[Name],
	IdCourse
	)
OUTPUT INSERTED.Id
VALUES (
	@Name,
	@IdCourse
	)
GO
PRINT N'Creating Procedure [EJournal].[GetCountGroupsByCourse]...';


GO
CREATE PROCEDURE [EJournal].[GetCountGroupsByCourse] @Id INT
AS
SELECT Count(G.Id)
FROM [EJournal].Groups G
WHERE G.IdCourse = @Id
GO
PRINT N'Creating Procedure [EJournal].[UpdateCourse]...';


GO
CREATE PROCEDURE [EJournal].[UpdateCourse] @Id INT,
	@Name NVARCHAR(100)
AS
UPDATE [EJournal].[Courses]
SET Name = @Name
WHERE Id = @Id
GO
PRINT N'Creating Procedure [EJournal].[GetCourse]...';


GO
CREATE PROCEDURE [EJournal].[GetCourse] @Id INT
AS
SELECT [Id],
	[Name]
FROM [EJournal].[Courses]
WHERE Id = @Id
	AND isDelete = 0
GO
PRINT N'Creating Procedure [EJournal].[GetAllCourses]...';


GO
CREATE PROCEDURE [EJournal].[GetAllCourses]
AS
SELECT [Id],
	[Name]
FROM [EJournal].[Courses]
WHERE IsDelete = 0
GO
PRINT N'Creating Procedure [EJournal].[DeleteCourse]...';


GO
CREATE PROCEDURE [EJournal].[DeleteCourse] @Id INT
AS
UPDATE [EJournal].[Courses]
SET IsDelete = 1
WHERE Id = @Id
GO
PRINT N'Creating Procedure [EJournal].[AddCourse]...';


GO
CREATE PROCEDURE [EJournal].[AddCourse] @Name NVARCHAR(100)
AS
INSERT INTO [EJournal].[Courses] (Name)
VALUES (@Name)
GO
PRINT N'Creating Procedure [EJournal].[AddExerciseToStudent]...';


GO
CREATE PROCEDURE [EJournal].[AddExerciseToStudent] @IdGroup INT,
	@Description NVARCHAR(250),
	@ExerciseType NVARCHAR(250),
	@Deadline DATETIME,
	@StudentExerciseVariable
AS
[EJournal].[StudentExercise] Readonly AS

DECLARE @IdExercise INT
DECLARE @StudentExercise AS [EJournal].[StudentExercise]

INSERT INTO @StudentExercise
SELECT *
FROM @StudentExerciseVariable

INSERT INTO [EJournal].[Exercises] (
	IdGroup,
	Description,
	Deadline
	)
VALUES (
	@IdGroup,
	@Description,
	@Deadline
	)

SET @IdExercise = SCOPE_IDENTITY()

UPDATE @StudentExercise
SET IdExercise = @IdExercise

INSERT INTO [EJournal].[StudentsExercises]
SELECT *
FROM @StudentExercise

RETURN @IdExercise
GO
PRINT N'Creating Procedure [EJournal].[AddGroupWithStudents]...';


GO
CREATE PROCEDURE [EJournal].[AddGroupWithStudents] @NameGroup NVARCHAR(100),
	@IdCourse INT,
	@IdsStudent
AS
[EJournal].[GroupIdsStudentsIds] readonly AS

DECLARE @IdGroup INT
DECLARE @GroupStudentsCopy AS [EJournal].[GroupIdsStudentsIds]

INSERT INTO @GroupStudentsCopy
SELECT *
FROM @IdsStudent

INSERT INTO [EJournal].[Groups] (
	Name,
	IdCourse
	)
VALUES (
	@NameGroup,
	@IdCourse
	)

SET @IdGroup = SCOPE_IDENTITY()

UPDATE @GroupStudentsCopy
SET IdGroup = @IdGroup

INSERT INTO [EJournal].[GroupStudents] (
	IdGroup,
	IdStudents
	)
SELECT *
FROM @GroupStudentsCopy

RETURN @IdGroup
GO
PRINT N'Creating Procedure [EJournal].[DeleteGroup]...';


GO
CREATE PROCEDURE [EJournal].[DeleteGroup] @IdGroup INT
AS
DELETE
FROM [EJournal].[Groups]
WHERE Id = @IdGroup
GO
PRINT N'Creating Procedure [EJournal].[GetStudentsNotAreInGroup]...';


GO
CREATE PROCEDURE [EJournal].[GetStudentsNotAreInGroup] @IdGroup INT
AS
SELECT S.[Id],
	S.[Name],
	S.[Surname],
	S.[Email],
	S.[Phone],
	S.[Git],
	S.[City],
	S.[Ranking],
	S.[AgreementNumber]
FROM [EJournal].[Students] S
WHERE S.IsDelete = 0
	AND Id NOT IN (
		SELECT IdStudents
		FROM [EJournal].GroupStudents
		WHERE IdGroup = @IdGroup
		)
ORDER BY S.Name
GO
PRINT N'Creating Procedure [EJournal].[GetStudentsNotInProjectGroup]...';


GO
CREATE PROCEDURE [EJournal].[GetStudentsNotInProjectGroup] @IdProjectGroup INT
AS
SELECT DISTINCT s.Id,
	s.Name,
	s.Surname,
	s.Phone,
	s.Email,
	s.Git,
	s.City,
	s.Ranking,
	s.TeacherAssessment,
	s.AgreementNumber,
	s.IsDelete
FROM [EJournal].[Students] AS s
WHERE S.IsDelete = 0
	AND Id NOT IN (
		SELECT IdStudent
		FROM [EJournal].StudetsProjectGroup
		WHERE IdProjectGroup = @IdProjectGroup
		)
ORDER BY S.Name
GO
PRINT N'Creating Procedure [EJournal].[GetLessonsByGroup]...';


GO
CREATE PROCEDURE [EJournal].[GetLessonsByGroup] @groupId INT
AS
SELECT L.[Id],
	L.[IdGroup],
	L.[DateLesson],
	L.[Topic]
FROM [EJournal].[Lessons] L
JOIN [EJournal].[Groups] G ON G.Id = L.IdGroup
WHERE G.Id = @groupId
GO
PRINT N'Creating Procedure [EJournal].[GetStudentsAttendancesByGroup]...';


GO
CREATE PROCEDURE [EJournal].[GetStudentsAttendancesByGroup] @GroupId INT
AS
SELECT L.[Id],
	L.DateLesson,
	L.Topic,
	S.Id IdStudent,
	S.Name,
	S.Surname,
	A.IsPresence
FROM [EJournal].[Lessons] L
JOIN [EJournal].[Groups] G ON G.Id = L.IdGroup
LEFT JOIN [EJournal].Attendances A ON A.IdLesson = L.Id
LEFT JOIN [EJournal].Students S ON A.IdStudent = S.Id
WHERE G.Id = @GroupId
ORDER BY L.DateLesson DESC
GO
PRINT N'Creating Procedure [EJournal].[UpdateLesson]...';


GO
CREATE PROCEDURE [EJournal].[UpdateLesson] @Id INT,
	@Topic NVARCHAR(250),
	@DateLesson DATETIME,
	@IdGroup INT
AS
UPDATE [EJournal].[Lessons]
SET Topic = @Topic,
	DateLesson = @DateLesson,
	IdGroup = @IdGroup
WHERE Id = @Id
GO
PRINT N'Creating Procedure [EJournal].[UpdateStudentsAttendances]...';


GO
CREATE PROCEDURE [EJournal].[UpdateStudentsAttendances] @StudentAttendance [EJournal].[StudentAttendance] READONLY,
	@Id INT,
	@Topic NVARCHAR(250),
	@DateLesson DATETIME
AS
UPDATE [EJournal].[Lessons]
SET DateLesson = @DateLesson,
	Topic = @Topic
WHERE Lessons.Id = @Id

MERGE [EJournal].[Attendances] AS A
USING @StudentAttendance AS SA
	ON SA.LessonsIds = A.IdLesson
		AND SA.StudentId = A.IdStudent
WHEN MATCHED
	THEN
		UPDATE
		SET A.IsPresence = SA.isPresense;
GO
PRINT N'Creating Procedure [EJournal].[GetLessons]...';


GO
CREATE PROCEDURE [EJournal].[GetLessons]
AS
SELECT [Id],
	[Topic],
	[DateLesson],
	[IdGroup]
FROM [EJournal].[Lessons]
GO
PRINT N'Creating Procedure [EJournal].[GetLesson]...';


GO
CREATE PROCEDURE [EJournal].[GetLesson] @Id INT
AS
SELECT [Id],
	[Topic],
	[DateLesson],
	[IdGroup]
FROM [EJournal].[Lessons]
WHERE Id = @Id
GO
PRINT N'Creating Procedure [EJournal].[DeleteLessonAndStudentsAttendances]...';


GO
CREATE PROCEDURE [EJournal].[DeleteLessonAndStudentsAttendances] @Id INT
AS
DELETE [EJournal].Attendances
WHERE IdLesson = @Id

DELETE [EJournal].Lessons
WHERE Id = @Id
GO
PRINT N'Creating Procedure [EJournal].[AddStudentsAttendance]...';


GO
CREATE PROCEDURE [EJournal].[AddStudentsAttendance] @Topic NVARCHAR(250),
	@DateLesson DATETIME,
	@IdGroup INT,
	@StudentAttendanceVariable
AS
[EJournal].[StudentAttendance] READONLY AS

DECLARE @IdLesson INT
DECLARE @StudentAttendance AS [EJournal].[StudentAttendance]

INSERT INTO @StudentAttendance
SELECT *
FROM @StudentAttendanceVariable

INSERT INTO [EJournal].Lessons (
	Topic,
	DateLesson,
	IdGroup
	)
VALUES (
	@Topic,
	@DateLesson,
	@IdGroup
	)

SET @IdLesson = SCOPE_IDENTITY()

UPDATE @StudentAttendance
SET LessonsIds = @IdLesson

INSERT INTO [EJournal].[Attendances] (
	IdLesson,
	IdStudent,
	IsPresence
	)
SELECT LessonsIds,
	StudentId,
	isPresense
FROM @StudentAttendance

RETURN @IdLesson
GO
PRINT N'Creating Procedure [EJournal].[GetStudentsByGroup]...';


GO
CREATE PROCEDURE [EJournal].[GetStudentsByGroup] @Id INT
AS
SELECT [Id],
	[Name],
	[Surname],
	[Email],
	[Phone],
	[Git],
	[City],
	[TeacherAssessment],
	[Ranking],
	[AgreementNumber]
FROM [EJournal].[Students] AS S
LEFT JOIN [EJournal].[GroupStudents] GS ON S.Id = GS.IdStudents
WHERE GS.IdGroup = @Id
	AND s.IsDelete = 0
GO
PRINT N'Creating Procedure [EJournal].[UpdateGroup]...';


GO
CREATE PROCEDURE [EJournal].[UpdateGroup] @Id INT,
	@Name NVARCHAR(100),
	@IdCourse INT
AS
UPDATE [EJournal].[Groups]
SET Name = @Name,
	IdCourse = @IdCourse
WHERE Id = @Id
GO
PRINT N'Creating Procedure [EJournal].[GetGroup]...';


GO
CREATE PROCEDURE [EJournal].[GetGroup] @Id INT
AS
SELECT [Id],
	[Name],
	[IdCourse],
	[IsFinish]
FROM [EJournal].[Groups]
WHERE Id = @Id
	AND IsDelete = 0
GO
PRINT N'Creating Procedure [EJournal].[GetAllGroupsWithCourses]...';


GO
CREATE PROCEDURE [EJournal].[GetAllGroupsWithCourses]
AS
SELECT c.Id,
	c.Name,
	g.Id,
	g.Name,
	g.IsFinish
FROM [EJournal].[Courses] c
INNER JOIN [EJournal].[Groups] g ON g.IdCourse = c.Id
GO
PRINT N'Creating Procedure [EJournal].[GetAllProjectGroups]...';


GO
CREATE PROCEDURE [EJournal].[GetAllProjectGroups] @IdProject INT
AS
SELECT pg.[Id],
	pg.[Name],
	pg.Mark
FROM [EJournal].ProjectGroups pg
INNER JOIN [EJournal].Projectes p ON p.Id = pg.IdProject
WHERE p.Id = @IdProject
GO
PRINT N'Creating Procedure [EJournal].[DeleteProjectGroup]...';


GO
CREATE PROCEDURE [EJournal].[DeleteProjectGroup] @Id INT
AS
DELETE [EJournal].[ProjectGroups]
WHERE Id = @Id
GO
PRINT N'Creating Procedure [EJournal].[DeleteProject]...';


GO
CREATE PROCEDURE [EJournal].[DeleteProject] @Id INT
AS
UPDATE [EJournal].[Projectes]
SET IsDelete = 1
WHERE Id = @Id
GO
PRINT N'Creating Procedure [EJournal].[AddStudentToProjectGroup]...';


GO
CREATE PROCEDURE [EJournal].AddStudentToProjectGroup @IdStudent INT,
	@IdProjectGroup INT
AS
INSERT INTO [EJournal].StudetsProjectGroup (
	IdStudent,
	IdProjectGroup
	)
VALUES (
	@IdStudent,
	@IdProjectGroup
	)
GO
PRINT N'Creating Procedure [EJournal].[AddProjectGroup]...';


GO
CREATE PROCEDURE [EJournal].[AddProjectGroup] @Name NVARCHAR(100),
	@IdProject INT
AS
INSERT INTO [EJournal].[ProjectGroups] (
	Name,
	IdProject
	)
VALUES (
	@Name,
	@IdProject
	)

SELECT CAST(SCOPE_IDENTITY() AS INT)
GO
PRINT N'Creating Procedure [EJournal].[AddProject]...';


GO
CREATE PROCEDURE [EJournal].[AddProject] @Name NVARCHAR(50),
	@Description NVARCHAR(255)
AS
INSERT INTO [EJournal].[Projectes] (
	Name,
	Description
	)
VALUES (
	@Name,
	@Description
	)

SELECT CAST(SCOPE_IDENTITY() AS INT)
GO
PRINT N'Creating Procedure [EJournal].[AddLesson]...';


GO
CREATE PROCEDURE [EJournal].[AddLesson] @Topic NVARCHAR(250),
	@DateLesson DATETIME,
	@IdGroup INT
AS
INSERT INTO [EJournal].[Lessons] (
	Topic,
	DateLesson,
	IdGroup
	)
VALUES (
	@Topic,
	Cast(@DateLesson AS DATETIME),
	@IdGroup
	)
GO
PRINT N'Creating Procedure [EJournal].[UpdateComment]...';


GO
CREATE PROCEDURE [EJournal].[UpdateComment] @Id INT,
	@Comments NVARCHAR(255),
	@CommentType NVARCHAR(100)
AS
UPDATE [EJournal].[Comments]
SET [CommentText] = @Comments,
	CommentType = @CommentType
WHERE Id = @Id
GO
PRINT N'Creating Procedure [EJournal].[DeleteComment]...';


GO
CREATE PROCEDURE [EJournal].[DeleteComment] @Id INT
AS
DELETE [EJournal].[Comments]
WHERE Id = @Id

DELETE [EJournal].[StudentsComments]
WHERE IdComment = @Id
GO
PRINT N'Creating Procedure [EJournal].[AddComment]...';


GO
CREATE PROCEDURE [EJournal].[AddComment] @IdStudent INT,
	@Comments NVARCHAR(255),
	@CommentType NVARCHAR(100)
AS
DECLARE @IdComment INT

INSERT INTO [EJournal].[Comments] (
	[EJournal].[Comments].[CommentText],
	[EJournal].[Comments].[CommentType]
	)
VALUES (
	@Comments,
	@CommentType
	)

SET @IdComment = SCOPE_IDENTITY()

INSERT INTO [EJournal].[StudentsComments] (
	IdComment,
	IdStudent
	)
VALUES (
	@IdComment,
	@IdStudent
	)

RETURN @IdComment;
GO
PRINT N'Creating Procedure [EJournal].[SearchByStudentGroup]...';


GO
CREATE PROCEDURE [EJournal].[SearchByStudentGroup] @Name NVARCHAR(50)
AS
SELECT s.[Id],
	s.[Name],
	s.[Surname],
	s.[Email],
	s.[Phone],
	s.[Git],
	s.[City],
	s.[Ranking],
	s.[AgreementNumber]
FROM [EJournal].[Students] S
LEFT JOIN [EJournal].[GroupStudents] GS ON GS.IdStudents = S.Id
LEFT JOIN [EJournal].[Groups] G ON G.Id = GS.IdGroup
WHERE S.IsDelete = 0
	AND G.[Name] LIKE ('%' + LTRIM(RTRIM(@Name)) + '%')
GO
PRINT N'Creating Procedure [EJournal].[SearchByStudentCourses]...';


GO
CREATE PROCEDURE [EJournal].[SearchByStudentCourses] @Name NVARCHAR(50)
AS
SELECT s.[Id],
	s.[Name],
	s.[Surname],
	s.[Email],
	s.[Phone],
	s.[Git],
	s.[City],
	s.[Ranking],
	s.[AgreementNumber]
FROM [EJournal].[Students] S
LEFT JOIN [EJournal].[GroupStudents] GS ON GS.IdStudents = S.Id
LEFT JOIN [EJournal].[Groups] G ON G.Id = GS.IdGroup
LEFT JOIN [EJournal].[Courses] C ON C.Id = G.IdCourse
WHERE S.IsDelete = 0
	AND C.[Name] LIKE ('%' + LTRIM(RTRIM(@Name)) + '%')
GO
PRINT N'Creating Procedure [EJournal].[SearchByStudentAgreementNumbers]...';


GO
CREATE PROCEDURE [EJournal].[SearchByStudentAgreementNumbers] @AgreementNumber NVARCHAR(50)
AS
SELECT [Id],
	[Name],
	[Surname],
	[Email],
	[Phone],
	[Git],
	[City],
	[Ranking],
	[AgreementNumber]
FROM [EJournal].[Students]
WHERE IsDelete = 0
	AND [AgreementNumber] LIKE ('%' + LTRIM(RTRIM(@AgreementNumber)) + '%')
GO
PRINT N'Creating Procedure [EJournal].[SearchByStudentCity]...';


GO
CREATE PROCEDURE [EJournal].[SearchByStudentCity] @City NVARCHAR(100)
AS
SELECT [Id],
	[Name],
	[Surname],
	[Email],
	[Phone],
	[Git],
	[City],
	[Ranking],
	[AgreementNumber]
FROM [EJournal].[Students]
WHERE IsDelete = 0
	AND City LIKE ('%' + LTRIM(RTRIM(@City)) + '%')
GO
PRINT N'Creating Procedure [EJournal].[SearchByStudentPhone]...';


GO
CREATE PROCEDURE [EJournal].[SearchByStudentPhone] @Phone NVARCHAR(50)
AS
SELECT [Id],
	[Name],
	[Surname],
	[Email],
	[Phone],
	[Git],
	[City],
	[Ranking],
	[AgreementNumber]
FROM [EJournal].[Students]
WHERE IsDelete = 0
	AND [Phone] LIKE ('%' + LTRIM(RTRIM(@Phone)) + '%')
GO
PRINT N'Creating Procedure [EJournal].[SearchStudentsByFullName]...';


GO
CREATE PROCEDURE [EJournal].[SearchStudentsByFullName] @Name NVARCHAR(100)
AS
SELECT [Id],
	[Name],
	[Surname],
	[Email],
	[Phone],
	[Git],
	[City],
	[Ranking],
	[AgreementNumber]
FROM [EJournal].[Students]
WHERE IsDelete = 0
	AND ([Name] + ' ' + [Surname]) LIKE ('%' + LTRIM(RTRIM(@Name)) + '%')
GO
PRINT N'Creating Procedure [EJournal].[SearchByStudentEmail]...';


GO
CREATE PROCEDURE [EJournal].[SearchByStudentEmail] @Email NVARCHAR(100)
AS
SELECT [Id],
	[Name],
	[Surname],
	[Email],
	[Phone],
	[Git],
	[City],
	[Ranking],
	[AgreementNumber]
FROM [EJournal].[Students]
WHERE IsDelete = 0
	AND Email LIKE '%' + @Email + '%';
GO
PRINT N'Creating Procedure [EJournal].[UpdateStudentRating]...';


GO
CREATE PROCEDURE [EJournal].[UpdateStudentRating] @IdStudent INT
AS
DECLARE @AttendanceCoef INT
DECLARE @TestCoef INT
DECLARE @HomeWorkCoef INT
DECLARE @TeacherAssessmentCoef INT
DECLARE @ProjectGroupCoef INT
DECLARE @Rating INT

SET @AttendanceCoef = (
		SELECT sum(cast(IsPresence AS INT) * 100)
		FROM [EJournal].[Attendances]
		WHERE IdStudent = @IdStudent
		) / (
		SELECT COUNT(IsPresence)
		FROM [EJournal].[Attendances]
		WHERE IdStudent = @IdStudent
		)

IF @AttendanceCoef IS NULL
	SET @AttendanceCoef = 100
SET @TestCoef = (
		SELECT SUM(SE.Point)
		FROM [EJournal].StudentsExercises SE
		LEFT JOIN [EJournal].[Exercises] E ON E.Id = SE.IdExercise
		WHERE SE.IdStudent = @IdStudent
			AND E.Deadline < GETDATE()
			AND E.ExerciseType = 'Test'
		) / (
		SELECT COUNT(IdExercise)
		FROM [EJournal].StudentsExercises SE
		LEFT JOIN [EJournal].[Exercises] E ON E.Id = SE.IdExercise
		WHERE SE.IdStudent = @IdStudent
			AND E.Deadline < GETDATE()
			AND E.ExerciseType = 'Test'
		)

IF @TestCoef IS NULL
	SET @TestCoef = 100
SET @HomeWorkCoef = (
		SELECT SUM(SE.Point)
		FROM [EJournal].StudentsExercises SE
		LEFT JOIN [EJournal].[Exercises] E ON E.Id = SE.IdExercise
		WHERE SE.IdStudent = @IdStudent
			AND E.Deadline < GETDATE()
			AND E.ExerciseType = 'HomeWork'
		) / (
		SELECT COUNT(IdExercise)
		FROM [EJournal].StudentsExercises SE
		LEFT JOIN [EJournal].[Exercises] E ON E.Id = SE.IdExercise
		WHERE SE.IdStudent = @IdStudent
			AND E.Deadline < GETDATE()
			AND E.ExerciseType = 'HomeWork'
		)

IF @HomeWorkCoef IS NULL
	SET @HomeWorkCoef = 100
SET @TeacherAssessmentCoef = (
		SELECT TeacherAssessment
		FROM [EJournal].[Students]
		WHERE id = @IdStudent
		)

IF @TeacherAssessmentCoef IS NULL
	SET @TeacherAssessmentCoef = 100
SET @ProjectGroupCoef = (
		SELECT PG.Mark
		FROM [EJournal].[ProjectGroups] PG
		LEFT JOIN [EJournal].[StudetsProjectGroup] SPG ON SPG.IdProjectGroup = PG.ID
		WHERE SPG.IdStudent = @IdStudent
		)

IF @ProjectGroupCoef IS NULL
	SET @ProjectGroupCoef = 100
SET @Rating = @AttendanceCoef * 0.15 + @TestCoef * 0.2 + @HomeWorkCoef * 0.25 + @TeacherAssessmentCoef * 0.2 + @ProjectGroupCoef * 0.2

UPDATE [EJournal].[Students]
SET Ranking = @Rating

RETURN @Rating
GO
PRINT N'Creating Procedure [EJournal].[GetCommentsByStudent]...';


GO
CREATE PROCEDURE [EJournal].[GetCommentsByStudent] @IdStudent INT
AS
SELECT [EJournal].[Comments].[Id],
	[EJournal].[Comments].[CommentText],
	[EJournal].[Comments].[CommentType]
FROM [EJournal].[StudentsComments]
INNER JOIN [EJournal].[Comments] ON [EJournal].[Comments].[Id] = [EJournal].[StudentsComments].[IdComment]
WHERE [EJournal].[StudentsComments].[IdStudent] = @IdStudent
GO
PRINT N'Creating Procedure [EJournal].[DeleteStudentExercise]...';


GO
CREATE PROCEDURE [EJournal].[DeleteStudentExercise] @Id INT
AS
DELETE [EJournal].StudentsExercises
WHERE IdExercise = @Id

DELETE [EJournal].Exercises
WHERE Id = @Id
GO
PRINT N'Creating Procedure [EJournal].[UpdateStudentExercise]...';


GO
CREATE PROCEDURE [EJournal].[UpdateStudentExercise] @Id INT,
	@IdGroup INT,
	@Description NVARCHAR(250),
	@ExerciseType NVARCHAR(250),
	@Deadline DATETIME,
	@StudentExercise
AS
[EJournal].[StudentExercise] Readonly AS

UPDATE [EJournal].[Exercises]
SET Description = @Description,
	Deadline = @Deadline,
	ExerciseType = @ExerciseType
WHERE Exercises.Id = @Id

MERGE [EJournal].[StudentsExercises] AS SE
USING @StudentExercise AS SEV
	ON SEV.IdStudent = SE.IdStudent
		AND SEV.IdExercise = SE.IdExercise
WHEN MATCHED
	THEN
		UPDATE
		SET SE.Point = SEV.Points;
GO
PRINT N'Creating Procedure [EJournal].[GetExercisesByGroup]...';


GO
CREATE PROCEDURE [EJournal].[GetExercisesByGroup] @IdGroup INT
AS
SELECT E.Id,
	E.Description,
	E.Deadline,
	E.IdGroup,
	E.ExerciseType,
	S.Id IdStudent,
	S.Name,
	S.Surname,
	SE.Point,
	SE.IdExercise
FROM [EJournal].Exercises E
INNER JOIN [EJournal].[Groups] G ON G.Id = E.IdGroup
LEFT JOIN [EJournal].StudentsExercises SE ON E.Id = SE.IdExercise
LEFT JOIN [EJournal].Students S ON SE.IdStudent = S.Id
WHERE G.Id = @IdGroup
ORDER BY E.Deadline
GO
PRINT N'Creating Procedure [EJournal].[UpdateGroupStudents]...';


GO
CREATE PROCEDURE [EJournal].[UpdateGroupStudents] @IdGroup INT,
	@NameGroup NVARCHAR(100),
	@IdCourse INT,
	@IdsAddStudent
AS
[EJournal].[GroupIdsStudentsIds] readonly,
	@IdsDeleteStudent AS [EJournal].[GroupIdsStudentsIds] readonly AS

UPDATE [EJournal].[Groups]
SET Name = @NameGroup,
	IdCourse = @IdCourse
WHERE Id = @IdGroup

DELETE
FROM [EJournal].[GroupStudents]
WHERE IdGroup = @IdGroup
	AND IdStudents IN (
		SELECT IdStudents
		FROM @IdsDeleteStudent
		)

INSERT INTO [EJournal].[GroupStudents] (
	IdGroup,
	IdStudents
	)
SELECT *
FROM @IdsAddStudent
GO
PRINT N'Creating Procedure [EJournal].[DeleteStudentsFromGroup]...';


GO
CREATE PROCEDURE [EJournal].[DeleteStudentsFromGroup] @IdsStudent
AS
[EJournal].[GroupIdsStudentsIds] readonly AS

CREATE TABLE #IdsStudent (
	IdGroup INT,
	IdStudent INT
	)

INSERT INTO #IdsStudent (
	IdGroup,
	IdStudent
	)
SELECT *
FROM @IdsStudent

DELETE
FROM [EJournal].[GroupStudents]
	--where [EJournal].[GroupStudents].IdGroup = #IdsStudent.IdGroup and IdStudents = #IdsStudent.IdStudent
GO
PRINT N'Creating Procedure [EJournal].[AddStudentsInGroup]...';


GO
CREATE PROCEDURE [EJournal].[AddStudentsInGroup] @IdsStudent
AS
[EJournal].[GroupIdsStudentsIds] readonly AS

INSERT INTO [EJournal].[GroupStudents] (
	IdGroup,
	IdStudents
	)
SELECT *
FROM @IdsStudent
GO
PRINT N'Creating Procedure [EJournal].[GetAllGroups]...';


GO
CREATE PROCEDURE [EJournal].[GetAllGroups]
AS
SELECT G.Id,
	G.Name,
	COUNT(S.Id) StudentsCount,
	C.Id AS IdCourse,
	C.Name AS NameCourse,
	G.IsFinish
FROM [EJournal].[Groups] G
LEFT JOIN [EJournal].Courses C ON C.Id = G.IdCourse
LEFT JOIN [EJournal].[GroupStudents] GS ON G.Id = GS.IdGroup
LEFT JOIN (
	SELECT S.Id
	FROM [EJournal].Students S
	WHERE S.IsDelete = 0
	) S ON S.Id = GS.IdStudents
WHERE G.IsDelete = 0
GROUP BY G.id,
	G.Name,
	C.Id,
	G.IsFinish,
	C.Name
GO
PRINT N'Creating Procedure [EJournal].[AddCommentToStudent]...';


GO
CREATE PROCEDURE [EJournal].[AddCommentToStudent] @CommentType NVARCHAR(100),
	@Comment NVARCHAR(255),
	@StudentCommentVarible
AS
[EJournal].[StudentsComment] READONLY AS

DECLARE @IdComment INT
DECLARE @StudentsComment AS [EJournal].[StudentsComment]

INSERT INTO @StudentsComment
SELECT *
FROM @StudentCommentVarible

INSERT INTO [EJournal].Comments (
	[CommentText],
	CommentType
	)
VALUES (
	@Comment,
	@CommentType
	)

SET @IdComment = SCOPE_IDENTITY()

UPDATE @StudentsComment
SET IdComment = @IdComment

INSERT INTO [EJournal].StudentsComments (
	IdStudent,
	IdComment
	)
SELECT IdStudent,
	IdComment
FROM @StudentsComment

RETURN @IdComment
GO
PRINT N'Creating Procedure [EJournal].[GetGroupAndStudentsInIt]...';


GO
CREATE PROCEDURE [EJournal].[GetGroupAndStudentsInIt] @IdGroup INT
AS
SELECT [EJournal].[Groups].[Id],
	[EJournal].[Students].[Id],
	[EJournal].[Students].[Name],
	[EJournal].[Students].[Surname],
	[EJournal].[Students].[Email],
	[EJournal].[Students].[Phone],
	[EJournal].[Students].[Git],
	[EJournal].[Students].[AgreementNumber]
FROM [EJournal].[GroupStudents]
INNER JOIN [EJournal].[Groups] ON [EJournal].[Groups].[Id] = [EJournal].[GroupStudents].[IdGroup]
INNER JOIN [EJournal].[Students] ON [EJournal].[Students].[Id] = [EJournal].[GroupStudents].[IdStudents]
WHERE [EJournal].[Groups].[Id] = @IdGroup
GO
PRINT N'Creating Procedure [EJournal].[GetGroupsAndNumberOfStudentsInThemAndGroupStatus]...';


GO
CREATE PROCEDURE [EJournal].[GetGroupsAndNumberOfStudentsInThemAndGroupStatus]
AS
SELECT GS.IdGroup,
	G.Name,
	COUNT(*) NumberOfStudents,
	G.IsFinish
FROM [EJournal].[GroupStudents] GS
INNER JOIN [EJournal].[Groups] G ON GS.IdGroup = G.Id
GROUP BY GS.IdGroup,
	G.Name,
	G.IsFinish
GO
PRINT N'Creating Procedure [EJournal].[GetStudentsFromProjectGroup]...';


GO
CREATE PROCEDURE [EJournal].[GetStudentsFromProjectGroup] @IdProjectGroup INT
AS
SELECT s.Id,
	s.Name,
	s.Surname,
	s.Phone,
	s.Email,
	s.Git,
	s.City,
	s.Ranking,
	s.TeacherAssessment,
	s.AgreementNumber,
	s.IsDelete
FROM [EJournal].[StudetsProjectGroup] AS spg
INNER JOIN [EJournal].[ProjectGroups] pg ON pg.Id = spg.IdProjectGroup
INNER JOIN [EJournal].[Students] AS s ON spg.IdStudent = s.Id
WHERE spg.IdProjectGroup = @IdProjectGroup
	AND s.IsDelete = 0
GO
PRINT N'Creating Procedure [EJournal].[GetAllStudents]...';


GO
CREATE PROCEDURE [EJournal].[GetAllStudents]
AS
SELECT [Id],
	[Name],
	[Surname],
	[Email],
	[Phone],
	[Git],
	[City],
	[TeacherAssessment],
	[Ranking],
	[AgreementNumber]
FROM [EJournal].[Students]
WHERE IsDelete = 0
GO
PRINT N'Creating Procedure [EJournal].[DeleteStudent]...';


GO
CREATE PROCEDURE [EJournal].[DeleteStudent] @Id INT
AS
UPDATE [EJournal].[Students]
SET IsDelete = 1
WHERE Id = @Id
GO
PRINT N'Creating Procedure [EJournal].[GetProject]...';


GO
CREATE PROCEDURE [EJournal].[GetProject] @Id INT
AS
SELECT [Name],
	[Description]
FROM [EJournal].[Projectes]
WHERE IsDelete = 0
	AND Id = @Id
GO
PRINT N'Creating Procedure [EJournal].[GetProjectGroup]...';


GO
CREATE PROCEDURE [EJournal].[GetProjectGroup] @Id INT
AS
SELECT [Id],
	[Name],
	[Mark]
FROM [EJournal].[ProjectGroups]
WHERE Id = @Id
GO
PRINT N'Creating Procedure [EJournal].[GetAllProjects]...';


GO
CREATE PROCEDURE [EJournal].[GetAllProjects]
AS
SELECT Id,
	Name,
	Description
FROM [EJournal].[Projectes]
WHERE IsDelete = 0
GO
PRINT N'Creating Procedure [EJournal].[UpdateProject]...';


GO
CREATE PROCEDURE [EJournal].[UpdateProject] @Id INT,
	@Name NVARCHAR(50),
	@Description NVARCHAR(255)
AS
UPDATE [EJournal].[Projectes]
SET Name = @Name,
	Description = @Description
WHERE Id = @Id
GO
PRINT N'Creating Procedure [EJournal].[UpdateProjectGroup]...';


GO
CREATE PROCEDURE [EJournal].[UpdateProjectGroup] @Id INT,
	@Name NVARCHAR(100),
	@Mark INT,
	@Students
AS
[EJournal].[StudentsIds] READONLY AS

UPDATE [EJournal].[ProjectGroups]
SET Name = @Name,
	Mark = @Mark
WHERE Id = @Id

DELETE
FROM StudetsProjectGroup
WHERE IdProjectGroup = @Id

INSERT INTO StudetsProjectGroup (
	IdProjectGroup,
	IdStudent
	)
SELECT IdProjectGroup,
	Idstudent
FROM @Students
GO
PRINT N'Creating Procedure [EJournal].[GetStudent]...';


GO
CREATE PROCEDURE [EJournal].[GetStudent] @Id INT
AS
SELECT [Id],
	[Name],
	[Surname],
	[Email],
	[Phone],
	[Git],
	[City],
	[TeacherAssessment],
	[Ranking],
	[AgreementNumber]
FROM [EJournal].[Students]
WHERE IsDelete = 0
	AND Id = @Id
GO
PRINT N'Creating Procedure [EJournal].[UpdateStudent]...';


GO
CREATE PROCEDURE [EJournal].[UpdateStudent] @Id INT,
	@Name NVARCHAR(100),
	@Surname NVARCHAR(100),
	@Email NVARCHAR(100),
	@Phone NVARCHAR(16),
	@Git NVARCHAR(100) = NULL,
	@City NVARCHAR(100) NULL,
	@TeacherAssessment INT,
	@AgreementNumber NVARCHAR(50)
AS
UPDATE [EJournal].[Students]
SET Name = @Name,
	Surname = @Surname,
	Email = @Email,
	Phone = @Phone,
	Git = @Git,
	City = @City,
	TeacherAssessment = @TeacherAssessment,
	AgreementNumber = @AgreementNumber
WHERE Id = @Id
GO
PRINT N'Creating Procedure [EJournal].[AddStudent]...';


GO
CREATE PROCEDURE [EJournal].[AddStudent] @Name NVARCHAR(100),
	@Surname NVARCHAR(100),
	@Email NVARCHAR(100),
	@Phone NVARCHAR(16),
	@Git NVARCHAR(100) = NULL,
	@City NVARCHAR(MAX),
	@Ranking INT,
	@AgreementNumber NVARCHAR(50)
AS
INSERT INTO [EJournal].[Students] (
	[Name],
	Surname,
	Email,
	Phone,
	Git,
	City,
	Ranking,
	AgreementNumber
	)
OUTPUT INSERTED.Id
VALUES (
	@Name,
	@Surname,
	@Email,
	@Phone,
	@Git,
	@City,
	@Ranking,
	@AgreementNumber
	)
GO
-- Refactoring step to update target server with deployed transaction logs

IF OBJECT_ID(N'dbo.__RefactorLog') IS NULL
BEGIN
    CREATE TABLE [dbo].[__RefactorLog] (OperationKey UNIQUEIDENTIFIER NOT NULL PRIMARY KEY)
    EXEC sp_addextendedproperty N'microsoft_database_tools_support', N'refactoring log', N'schema', N'dbo', N'table', N'__RefactorLog'
END
GO
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'c76c9f35-9d70-4e3e-b377-ddd7802de44f')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('c76c9f35-9d70-4e3e-b377-ddd7802de44f')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'e1cbb174-0180-4db5-abaa-f7d88b6e7a38')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('e1cbb174-0180-4db5-abaa-f7d88b6e7a38')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '51c83756-1b2e-4a1b-8bf7-7b137008ff79')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('51c83756-1b2e-4a1b-8bf7-7b137008ff79')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '5492cd3d-bf97-41f7-a239-1d865c558482')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('5492cd3d-bf97-41f7-a239-1d865c558482')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '84d881a3-5cf0-4c95-ba65-63c531de6b9d')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('84d881a3-5cf0-4c95-ba65-63c531de6b9d')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '4e5f0da8-588c-4282-abcf-9bb0a6685e39')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('4e5f0da8-588c-4282-abcf-9bb0a6685e39')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'e9320d15-4402-4ba8-95c6-34792dc19582')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('e9320d15-4402-4ba8-95c6-34792dc19582')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'd12f3314-a6e4-4bb2-b4c8-b9d24e978a44')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('d12f3314-a6e4-4bb2-b4c8-b9d24e978a44')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '22a2eff6-3c1c-43bf-a4ef-478170643093')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('22a2eff6-3c1c-43bf-a4ef-478170643093')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '0c1e13ce-2f71-44ff-9a56-fa529799cec1')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('0c1e13ce-2f71-44ff-9a56-fa529799cec1')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '4d18e2a9-66cd-4f34-b3a0-4afb890d917b')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('4d18e2a9-66cd-4f34-b3a0-4afb890d917b')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'cb0539ca-5113-4ef0-a7d7-165953408f25')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('cb0539ca-5113-4ef0-a7d7-165953408f25')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '911940ea-3372-4251-b813-3afb0e247958')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('911940ea-3372-4251-b813-3afb0e247958')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '9102c62f-df54-4013-8675-95426358be13')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('9102c62f-df54-4013-8675-95426358be13')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '65325c3c-8318-4db5-b28f-3608a19ba5aa')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('65325c3c-8318-4db5-b28f-3608a19ba5aa')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '3f18f33f-5cb6-494b-ab79-e0c72a0fd0c0')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('3f18f33f-5cb6-494b-ab79-e0c72a0fd0c0')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '92947128-73ca-4eab-a1c5-4864bef6be3e')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('92947128-73ca-4eab-a1c5-4864bef6be3e')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'f8233e83-6691-45db-a15e-267dc882eda3')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('f8233e83-6691-45db-a15e-267dc882eda3')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '2149a70d-5424-437e-b07b-0a68f41ce784')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('2149a70d-5424-437e-b07b-0a68f41ce784')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '3fbbcb5a-e21e-42fc-8efb-ebae4b3b71ed')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('3fbbcb5a-e21e-42fc-8efb-ebae4b3b71ed')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '4b062bd7-d292-4df2-8127-a02f2a0b1d8e')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('4b062bd7-d292-4df2-8127-a02f2a0b1d8e')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'e51d908f-eb35-4b7f-bbf2-dff852b0b714')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('e51d908f-eb35-4b7f-bbf2-dff852b0b714')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'a2cb90ba-7243-4c52-8288-00b3b3e4f02c')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('a2cb90ba-7243-4c52-8288-00b3b3e4f02c')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'd023875f-9fdf-4f34-a14d-1b136456bad8')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('d023875f-9fdf-4f34-a14d-1b136456bad8')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'e33188be-4438-4f68-833d-96096257fb50')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('e33188be-4438-4f68-833d-96096257fb50')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'f911cc75-65e7-4edd-8253-713e290da397')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('f911cc75-65e7-4edd-8253-713e290da397')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '1b8afff2-9642-48c9-a11f-4a3f083a2831')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('1b8afff2-9642-48c9-a11f-4a3f083a2831')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'f22d4a80-cc30-4e09-a102-98fdd5873e62')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('f22d4a80-cc30-4e09-a102-98fdd5873e62')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '1d0e8087-3307-4783-b986-1b3c033f7711')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('1d0e8087-3307-4783-b986-1b3c033f7711')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '949971e8-3af4-40f1-bbe3-14069ff2f8bf')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('949971e8-3af4-40f1-bbe3-14069ff2f8bf')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '1b14a86d-3c7a-438c-b1ab-108693c07be3')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('1b14a86d-3c7a-438c-b1ab-108693c07be3')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '20688625-2990-4672-8f4e-3355c2501504')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('20688625-2990-4672-8f4e-3355c2501504')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'f8befadf-c09f-4901-94d3-3c85eada6b24')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('f8befadf-c09f-4901-94d3-3c85eada6b24')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '8fa63505-caef-47fd-9993-c48fb10900cd')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('8fa63505-caef-47fd-9993-c48fb10900cd')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '8f70e344-bef6-48df-9cef-467f1f2b4388')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('8f70e344-bef6-48df-9cef-467f1f2b4388')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'b81b07bf-d378-495e-bf54-ad79ca9cc9c0')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('b81b07bf-d378-495e-bf54-ad79ca9cc9c0')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '7350b9cf-a45b-48fa-9ae3-429ab85f8526')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('7350b9cf-a45b-48fa-9ae3-429ab85f8526')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '0c30a566-cd2f-4dcc-8ab7-5e2e3fdb2914')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('0c30a566-cd2f-4dcc-8ab7-5e2e3fdb2914')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '4551274c-5889-436c-b349-7f7894d629b2')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('4551274c-5889-436c-b349-7f7894d629b2')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '5469a293-29e0-4efd-bcd7-86cbe74417f4')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('5469a293-29e0-4efd-bcd7-86cbe74417f4')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'b3301991-52c1-421a-927c-0130936eb069')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('b3301991-52c1-421a-927c-0130936eb069')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'de7011f7-0426-4212-8f06-4327939311a2')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('de7011f7-0426-4212-8f06-4327939311a2')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '7123f726-1a02-4157-833a-d69c0ededff2')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('7123f726-1a02-4157-833a-d69c0ededff2')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '2f610d05-7c82-4a45-8a90-211807b75e62')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('2f610d05-7c82-4a45-8a90-211807b75e62')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '9e8d6164-b610-4133-9bfc-eeaab7910de6')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('9e8d6164-b610-4133-9bfc-eeaab7910de6')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '699c3874-d9b3-4f39-a007-e8a5d1dd0ffe')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('699c3874-d9b3-4f39-a007-e8a5d1dd0ffe')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '6a21a3db-c013-4499-b72c-c3e48080b130')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('6a21a3db-c013-4499-b72c-c3e48080b130')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '612020c7-4a59-4426-b8b9-bbed128e664f')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('612020c7-4a59-4426-b8b9-bbed128e664f')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '3d252922-a645-4714-9c55-7aadb517841a')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('3d252922-a645-4714-9c55-7aadb517841a')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '03896420-7dfe-4c76-9240-41b771dfe8fe')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('03896420-7dfe-4c76-9240-41b771dfe8fe')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'ba3f7240-9ca9-4fd0-9ef3-3717107907f9')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('ba3f7240-9ca9-4fd0-9ef3-3717107907f9')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '5d0a958d-e107-4cdb-bb67-e9a6ee5aab76')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('5d0a958d-e107-4cdb-bb67-e9a6ee5aab76')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'ff09aff9-5a15-4b59-b82e-71c8a28542bc')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('ff09aff9-5a15-4b59-b82e-71c8a28542bc')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '82428f47-776b-4c41-afe4-b5031e13ce17')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('82428f47-776b-4c41-afe4-b5031e13ce17')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '048c54df-157f-4bd4-a496-b118ab86d11d')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('048c54df-157f-4bd4-a496-b118ab86d11d')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'e03757eb-2efa-47a4-b9e4-0c209b5de448')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('e03757eb-2efa-47a4-b9e4-0c209b5de448')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '77fcbbbf-4fe0-4847-a43b-2f342c44ee38')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('77fcbbbf-4fe0-4847-a43b-2f342c44ee38')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'd6c0fc37-c92e-4184-9a88-0ba0b50d4c46')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('d6c0fc37-c92e-4184-9a88-0ba0b50d4c46')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '9e790da1-75a4-4245-8b29-b14722f0e59e')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('9e790da1-75a4-4245-8b29-b14722f0e59e')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '92cc071b-3a60-45e1-ba85-d3a74b510bf6')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('92cc071b-3a60-45e1-ba85-d3a74b510bf6')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '623bfe98-41b2-4896-a8ba-a78d80122e35')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('623bfe98-41b2-4896-a8ba-a78d80122e35')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'd2117cef-43d5-4877-a4d8-2dc28be721c5')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('d2117cef-43d5-4877-a4d8-2dc28be721c5')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'd26343e3-9855-43c8-b574-068b03326b22')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('d26343e3-9855-43c8-b574-068b03326b22')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '277a0e55-de0b-4c3c-a7ce-39e8f21cc7ca')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('277a0e55-de0b-4c3c-a7ce-39e8f21cc7ca')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'b3d16265-df13-4a31-845a-08ddb69007de')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('b3d16265-df13-4a31-845a-08ddb69007de')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '63efc32e-2ffd-4db9-b143-46dad000cf68')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('63efc32e-2ffd-4db9-b143-46dad000cf68')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '97f1cf5a-61cd-40e5-ba57-5cca0accbaba')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('97f1cf5a-61cd-40e5-ba57-5cca0accbaba')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '8206096c-9347-4015-ab89-e4156888a263')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('8206096c-9347-4015-ab89-e4156888a263')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'fdf24e13-66ea-4c27-8420-cf0bbcf72cac')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('fdf24e13-66ea-4c27-8420-cf0bbcf72cac')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'c19a56f0-6639-4fb0-867d-48b28dad8b6a')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('c19a56f0-6639-4fb0-867d-48b28dad8b6a')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '35b3281f-3f99-4bbb-ba93-3a98c08e08f1')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('35b3281f-3f99-4bbb-ba93-3a98c08e08f1')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '902b0ff0-5984-40d3-b026-717ef143073e')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('902b0ff0-5984-40d3-b026-717ef143073e')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '5ef66b66-750e-44be-8a9d-a3cc591e7b2c')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('5ef66b66-750e-44be-8a9d-a3cc591e7b2c')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '6f986ea6-2516-4041-9c95-3ced1e4093ad')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('6f986ea6-2516-4041-9c95-3ced1e4093ad')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '5475933e-a26a-4ae6-8432-1ec3f57681dc')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('5475933e-a26a-4ae6-8432-1ec3f57681dc')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'e9e19888-cbd1-44ab-b0c3-012314bce07b')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('e9e19888-cbd1-44ab-b0c3-012314bce07b')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'c5332ce7-208c-4194-b7eb-d58b5754613d')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('c5332ce7-208c-4194-b7eb-d58b5754613d')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '7547b7ec-41bf-41f7-9ed8-8ea776e11a80')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('7547b7ec-41bf-41f7-9ed8-8ea776e11a80')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '485ca62c-8589-4d38-acc4-5017c154acd2')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('485ca62c-8589-4d38-acc4-5017c154acd2')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'd78e75b1-2029-46f3-aa81-cd237f32a9c8')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('d78e75b1-2029-46f3-aa81-cd237f32a9c8')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '69bdbe73-0e5f-499e-b1d5-016355635c15')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('69bdbe73-0e5f-499e-b1d5-016355635c15')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'c918fe73-45aa-41e4-8831-4d7db2f1d497')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('c918fe73-45aa-41e4-8831-4d7db2f1d497')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '807f19f4-d716-4671-821b-80ac9faaa589')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('807f19f4-d716-4671-821b-80ac9faaa589')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'bf1efd99-2760-450b-8394-354e7422a14d')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('bf1efd99-2760-450b-8394-354e7422a14d')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '463d532d-8a3f-4e7f-933c-39a7f3e08c32')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('463d532d-8a3f-4e7f-933c-39a7f3e08c32')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '23f28e1e-9a25-42f0-856f-d11e6023f32f')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('23f28e1e-9a25-42f0-856f-d11e6023f32f')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '95371095-7ce9-4c01-adec-0a5914daaba3')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('95371095-7ce9-4c01-adec-0a5914daaba3')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '3a046aa4-31d9-4b50-9f15-65689196b639')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('3a046aa4-31d9-4b50-9f15-65689196b639')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'f7d6fce3-af2d-44a0-9f56-0cc295c9ae80')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('f7d6fce3-af2d-44a0-9f56-0cc295c9ae80')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'ede7f9c9-d388-4f29-aa2c-da753bb404fa')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('ede7f9c9-d388-4f29-aa2c-da753bb404fa')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '7d3e1348-bf60-473b-a7d3-638252fac761')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('7d3e1348-bf60-473b-a7d3-638252fac761')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'd8dc6697-1576-427d-941e-8b953900518f')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('d8dc6697-1576-427d-941e-8b953900518f')

GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [EJournal].[Attendances] WITH CHECK CHECK CONSTRAINT [Attendances_Lessons_Id];


GO
PRINT N'Update complete.';


GO
